management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

server:
  servlet:
    context-path: /admin
  port: 9090

spring:
  security:
    user:
      name: admin
      password: 123456
