#nacos:
#  config:
#    server-addr: 127.0.0.1:8848
#    data-id: dtp.yaml
#    type: yaml
#    auto-refresh: true
#    bootstrap:
#      enable: true

dtp:
  executor:
    - pool-name: p1
      core-pool-size: 5
      maximum-pool-size: 50
    - pool-name: p2
      core-pool-size: 55

